//! The CLI adapter.
//!
//! It owns argv, the two output forms, and the process exit code — nothing else. Every
//! sentence it prints was generated by `montaget_core::text` from the canonical JSON.

use std::ffi::OsString;
use std::path::PathBuf;
use std::process::ExitCode;

use clap::{Parser, Subcommand};
use montaget_core::report::Report;
use montaget_core::text;

#[derive(Parser)]
#[command(
    name = "montaget",
    version,
    about = "A video editor whose project format is authored by an agent.",
    disable_help_subcommand = true
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Does the document agree with itself and with the disk?
    Validate {
        /// The project file.
        project: PathBuf,
        /// Print the canonical JSON *instead of* the text report, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },
    /// Serve the MCP tools over stdio.
    ///
    /// Not one of ADR-0011's nine verbs: the verbs are what an agent calls, and this is
    /// how the agent's client starts the process that offers them.
    Mcp,
}

pub fn run<I, T>(args: I) -> ExitCode
where
    I: IntoIterator<Item = T>,
    T: Into<OsString> + Clone,
{
    let cli = match Cli::try_parse_from(args) {
        Ok(cli) => cli,
        Err(e) if e.use_stderr() => {
            // ADR-0011: an invocation error is a finding, with the same object and the
            // same stable codes as everything else, so there is exactly one thing to
            // parse across the surface.
            let report = Report::bad_invocation(e.to_string().trim_end());
            eprint!("{}", render(&report, false));
            return exit_code(&report);
        }
        // `--help` and `--version` are not failures; clap has the text, and it goes to
        // stdout with a zero exit.
        Err(e) => {
            print!("{e}");
            return ExitCode::SUCCESS;
        }
    };

    match cli.command {
        Command::Validate {
            project,
            json,
            verbose,
        } => {
            let report = montaget_core::validate(&project);
            if json {
                println!(
                    "{}",
                    serde_json::to_string_pretty(&report.to_json()).expect("report JSON")
                );
            } else {
                print!("{}", render(&report, verbose));
            }
            exit_code(&report)
        }
        Command::Mcp => match crate::mcp::serve() {
            Ok(()) => ExitCode::SUCCESS,
            Err(e) => {
                let report = Report::internal_failure(e);
                eprint!("{}", render(&report, false));
                exit_code(&report)
            }
        },
    }
}

fn render(report: &Report, verbose: bool) -> String {
    let options = if verbose {
        text::Options::verbose()
    } else {
        text::Options::default()
    };
    let json = report.to_json();
    match text::render(&json, options) {
        Ok(rendered) => rendered,
        // The renderer only fails when a finding's code has no registered template,
        // which is a bug in Montaget rather than a fact about the project. Say so in
        // the one wire format that cannot itself fail.
        Err(e) => format!("montaget could not render its own report: {e}\n{json}\n"),
    }
}

fn exit_code(report: &Report) -> ExitCode {
    ExitCode::from(report.exit_code().as_u8())
}
