//! The CLI adapter.
//!
//! It owns argv, the two output forms, and the process exit code — nothing else. Every
//! sentence it prints was generated by `montaget_core::text` from the canonical JSON.

use std::ffi::OsString;
use std::path::PathBuf;
use std::process::ExitCode;

use clap::{Parser, Subcommand};
use montaget_core::Wire;
use montaget_core::report::Report;

#[derive(Parser)]
#[command(
    name = "montaget",
    version,
    about = "A video editor whose project format is authored by an agent.",
    disable_help_subcommand = true
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Does the document agree with itself and with the disk?
    Validate {
        /// The project file.
        project: PathBuf,
        /// Print the canonical JSON *instead of* the text report, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },
    /// Scaffold a legal, empty project file.
    ///
    /// ADR-0011's `create_project`: so the agent never starts from a blank file and
    /// invents a shape. It never overwrites, and it writes no header field that was not
    /// asked for (ADR-0030).
    #[command(name = "create-project", alias = "create_project")]
    CreateProject {
        /// The project file to create. It must not already exist.
        project: PathBuf,
        /// Frame width in pixels.
        #[arg(long)]
        width: i64,
        /// Frame height in pixels.
        #[arg(long)]
        height: i64,
        /// Frames per second.
        #[arg(long)]
        fps: i64,
        /// Background colour, `#RRGGBB` or `#RRGGBBAA`, uppercase.
        #[arg(long)]
        background: Option<String>,
        /// The project's intended length, in whole milliseconds.
        #[arg(long)]
        duration: Option<i64>,
        /// Where `render` writes the video, relative to the project file.
        #[arg(long)]
        output: Option<String>,
        /// Print the canonical JSON *instead of* the text report, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },
    /// Rewrite the file in the canonical convention.
    ///
    /// CLI-only (ADR-0011), and split in two (ADR-0041): `--check` reports what a
    /// rewrite would change and writes nothing; bare `fmt` writes.
    Fmt {
        /// The project file.
        project: PathBuf,
        /// Report what a rewrite would change, without touching the file.
        #[arg(long)]
        check: bool,
        /// Print the canonical JSON *instead of* the text report, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },
    /// What are this media file's numbers?
    ///
    /// CLI-only (ADR-0011): an MCP tool schema costs the agent context on every turn,
    /// and a subcommand costs nothing until invoked.
    Probe {
        /// The media files or URLs to probe. A relative path resolves against the working
        /// directory (ADR-0053).
        #[arg(required = true)]
        sources: Vec<String>,
        /// Print the canonical JSON *instead of* the text report, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },
    /// Print the project's wide view.
    ///
    /// CLI-only (ADR-0011): this is the *human's* view, and the one verb whose reader is
    /// not the agent. It offers no verbosity switch, because it has no informational
    /// findings to expand — the view itself is the answer, and it is never collapsed.
    Timeline {
        /// The project file.
        project: PathBuf,
        /// Print the canonical JSON *instead of* the text view, never alongside it.
        #[arg(long)]
        json: bool,
    },

    /// What is true at an instant, over a range, or across a predicate?
    ///
    /// ADR-0011's three modes. `--at` returns the resolved stack at one instant — who is
    /// present, in painter's order, with every animated value resolved rather than echoed.
    /// `--from --to` returns the cut list — the intervals over which the presence set is
    /// constant, with the boundary immediately outside the range named on each side.
    /// `--where` returns the matched set, and `--census` its distribution over one field.
    /// None of them reads the disk, and only `--at` resolves anything: the other two match a
    /// value as the document writes it.
    ///
    /// It offers no verbosity switch, because it has no informational findings to
    /// expand — the answer itself is the output, and it is never collapsed.
    Query {
        /// The project file.
        project: PathBuf,
        /// The instant to resolve the stack at, in absolute milliseconds.
        #[arg(long, value_name = "MS")]
        at: Option<i64>,
        /// The start of the range, in absolute milliseconds. Asked for with `--to`.
        #[arg(long, value_name = "MS")]
        from: Option<i64>,
        /// The end of the range, exclusive: a range is half-open `[from, to)`.
        #[arg(long, value_name = "MS")]
        to: Option<i64>,
        /// Which elements to match, e.g. `type = text and group = item-05`.
        ///
        /// Terms are `<field> <op> <value>`, `<field> exists` or `<field> missing`, joined
        /// with `and` — there is no `or`, and two calls answer one. `<op>` is one of `=`,
        /// `!=`, `<`, `<=`, `>`, `>=`. A field is a dotted path into the element —
        /// `clip.width`, `runs.*.font`, `runs.0.font` — plus the reserved `track`, which is
        /// the name of the track the element sits in. A bare value reads as the JSON scalar
        /// it spells and quoting forces a string, so `loop = true` is the boolean and
        /// `id = "true"` the word. Values match **whole** — no substrings — **as the
        /// document writes them**; nothing is resolved. A term holds if any value the path
        /// reaches satisfies it, which is what makes `runs.*.font = brand` "has a run whose
        /// font is brand". (ADR-0070)
        #[arg(long = "where", value_name = "PREDICATE")]
        predicate: Option<String>,
        /// Distribute the matched set over this field.
        #[arg(long, value_name = "FIELD")]
        census: Option<String>,
        /// Print the canonical JSON *instead of* the text answer, never alongside it.
        #[arg(long)]
        json: bool,
    },

    /// What does it look like right now?
    ///
    /// One instant, rasterized at the project's true pixel dimensions and answered as
    /// **JPEG at half that size** — full scale and PNG are behind flags, because an image
    /// costs an agent `⌈w/28⌉ × ⌈h/28⌉` visual tokens whatever it is encoded as: 2691 at
    /// 1080×1920 against 700 at 540×960 (ADR-0011).
    ///
    /// The `query --at` block prints alongside the picture **unconditionally** — there is no
    /// flag that suppresses it, because looking at a frame without knowing which elements
    /// produced it is how a defect gets attributed to the wrong one.
    ///
    /// It offers no verbosity switch, for the same reason `query` offers none: the answer
    /// itself is the output and is never collapsed.
    Frame {
        /// The project file.
        project: PathBuf,
        /// The instant to draw, in absolute milliseconds.
        #[arg(long, value_name = "MS")]
        at: Option<i64>,
        /// Where to write the picture.
        ///
        /// Required, and deliberately not defaulted: no ADR names a filename for this, and
        /// a verb that invented one would be writing a file into somebody's project
        /// directory on a read. The MCP surface needs no such flag — there the image comes
        /// back in the answer.
        #[arg(long, value_name = "PATH")]
        out: PathBuf,
        /// Return just this region of the frame, as `x,y,w,h` in whole frame-space pixels
        /// at true scale — so you can look closely at one card without paying for the
        /// whole canvas.
        #[arg(long, value_name = "X,Y,W,H")]
        crop: Option<String>,
        /// True pixel dimensions instead of half scale. You are asking for 2691 tokens
        /// rather than 700, and that is the whole of what this flag does.
        #[arg(long)]
        full: bool,
        /// PNG instead of JPEG. Costs the same tokens (they are a function of decoded
        /// pixels), and buys lossless pixels for more bytes and more latency.
        #[arg(long)]
        png: bool,
        /// Print the canonical JSON *instead of* the text answer, never alongside it.
        #[arg(long)]
        json: bool,
    },

    /// What does this text actually occupy, in the fonts the project declares? Or, given
    /// `--at` instead, the nearest sampled instant at-or-before a time, on the project's
    /// own frame grid (ADR-0035).
    ///
    /// `--element` takes the text element itself, as JSON — the same shape you are about
    /// to write into the file, and the shape `montaget://schema.json` publishes. It needs
    /// no `id` and need not exist in the file yet (ADR-0024). `--at` takes a time instead,
    /// and answers a different question. `--elements` takes an array of specs in the same
    /// shape, and `--all` asks about every text element the project already has — the
    /// batch mode (#317); one bad element in a batch reports its own error rather than
    /// failing the other slots. Exactly one of the four may be given.
    ///
    /// It offers no verbosity switch, because it has no informational findings to expand —
    /// the answer itself is the output, and it is never collapsed.
    Measure {
        /// The project file. Its `fonts` table is what the element's `font` is a key
        /// into; its `fps` is what `--at` resolves against.
        project: PathBuf,
        /// The text element, as JSON: `runs`, `font`, `size`, and optionally
        /// `line_height`, `y`, `origin` and `stroke_width`. Any other field is ignored —
        /// `width` and `height` included, because `measure` derives and never judges
        /// (ADR-0024). Exclusive with `--at`, `--elements` and `--all`.
        #[arg(long, value_name = "JSON")]
        element: Option<String>,
        /// A time, in absolute milliseconds, to resolve against the project's frame grid
        /// instead of measuring an element: the nearest sampled instant at-or-before it
        /// (ADR-0035), so a fade can be retargeted to land on it exactly. Exclusive with
        /// `--element`, `--elements` and `--all`.
        #[arg(long, value_name = "MS")]
        at: Option<i64>,
        /// A JSON array of element specs, each in `--element`'s own shape — the batch
        /// primitive (#317). None need exist in the project file. A malformed array is
        /// refused outright; one unmeasurable element inside a well-formed array reports
        /// its own error and the rest of the batch still answers. Exclusive with
        /// `--element`, `--at` and `--all`.
        #[arg(long, value_name = "JSON")]
        elements: Option<String>,
        /// Every text element the project already has, fed through the same batch engine
        /// `--elements` uses (#317) — no id-listing required. An empty project answers
        /// with an empty batch, not an error. Exclusive with `--element`, `--at` and
        /// `--elements`.
        #[arg(long)]
        all: bool,
        /// Print the canonical JSON *instead of* the text answer, never alongside it.
        #[arg(long)]
        json: bool,
    },

    /// Files in, video out — and the enforcement point for every check.
    ///
    /// Runs the identical check engine `validate` runs and refuses on any `error`
    /// (ADR-0006): the check cannot be skipped by not running it. A `LAYOUT` finding never
    /// gates it (ADR-0041). The video is written to the project's declared `output` via a
    /// temp path and an atomic rename, so a truncated MP4 never reads as finished.
    ///
    /// After a successful render it prints the `review` findings it did not refuse on and
    /// the `NOT CHECKED` footer — exit 0 never means "the video is right". The
    /// machine-readable result goes to stdout; coarse progress goes to stderr.
    Render {
        /// The project file.
        project: PathBuf,
        /// Render only from this instant, in absolute milliseconds. Asked for with `--to`.
        /// A partial render is written to `out/<name>.<from>-<to>.mp4`, never to the
        /// project's `output`.
        #[arg(long, value_name = "MS")]
        from: Option<i64>,
        /// The end of the partial range, exclusive: the range is half-open `[from, to)`.
        #[arg(long, value_name = "MS")]
        to: Option<i64>,
        /// Write here instead of the project's `output`. Refused while a range is set if
        /// it names the project's own `output`.
        #[arg(long, value_name = "PATH")]
        output: Option<PathBuf>,
        /// Print the canonical JSON *instead of* the text result, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },

    /// Does it look right in motion? A scrub preview at a proxy resolution.
    ///
    /// Renders at the 720p proxy target — the long edge capped at 1280 px, aspect
    /// preserved, rounded to even (ADR-0046) — so a scrub stays under five seconds. A span
    /// that runs past that budget degrades exactly once, to 540p, and hard-fails rather
    /// than degrade again (ADR-0065). **The tier is disclosed every time**, degraded or
    /// not: it is how you know what you are looking at (ADR-0021).
    ///
    /// Never the deliverable — the preview is written to
    /// `out/<name>.preview.<from>-<to>.mp4`, and `--output` naming the project's own
    /// `output` is refused. `render` is never degraded (ADR-0067); use `frame` when you
    /// need true pixels of one instant.
    Preview {
        /// The project file.
        project: PathBuf,
        /// Preview only from this instant, in absolute milliseconds. Asked for with
        /// `--to`.
        #[arg(long, value_name = "MS")]
        from: Option<i64>,
        /// The end of the scrub, exclusive: the range is half-open `[from, to)`.
        #[arg(long, value_name = "MS")]
        to: Option<i64>,
        /// Write here instead of `out/<name>.preview.<from>-<to>.mp4`. Refused where it
        /// names the project's own `output`.
        #[arg(long, value_name = "PATH")]
        output: Option<PathBuf>,
        /// True pixels instead of the proxy target, for a check that is precision-
        /// sensitive. This arm of the budget is observational: it is neither enforced nor
        /// degraded, and you are paying for what you asked for (ADR-0021).
        #[arg(long)]
        full: bool,
        /// Print the canonical JSON *instead of* the text result, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },

    /// Move every time at or after an instant.
    ///
    /// The one edit that is arithmetic rather than authorship (ADR-0005, ADR-0012). Refuses
    /// a straddling time-based element, and refuses any edit that would change an existing
    /// slack's size unless `--release` names it (ADR-0032, ADR-0047). Prints what it will do
    /// to every record sitting exactly at `--at`, unconditionally (ADR-0036). Returns the new
    /// state's findings, never `ok` (ADR-0011).
    Shift {
        /// The project file.
        project: PathBuf,
        /// The instant to shift at or after, in absolute milliseconds.
        #[arg(long, value_name = "MS")]
        at: i64,
        /// The offset, in milliseconds. Must be positive.
        #[arg(long, value_name = "MS")]
        delta: i64,
        /// Narrow the edit to one track. Defaults to the whole project.
        #[arg(long, value_name = "TRACK")]
        scope: Option<String>,
        /// A slack this edit would otherwise change, named as `FROM,TO` — its full
        /// boundary-instant pair, exactly as a refusal reports it. Repeatable; there is no
        /// bulk form.
        #[arg(long = "release", value_name = "FROM,TO")]
        release: Vec<String>,
        /// Print the canonical JSON *instead of* the text report, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },

    /// What changed between two versions of the timeline?
    ///
    /// Reports drift — slack, keyframe-instant relationships, boundary-coincidence
    /// clusters, highlight text — as facts with no severity (#221): it describes what
    /// changed, it never judges it, and `render` never consults its output.
    Compare {
        /// The prior version of the project file.
        #[arg(value_name = "REF")]
        reference: PathBuf,
        /// The current version of the project file.
        #[arg(value_name = "CURRENT")]
        current: PathBuf,
        /// Print the canonical JSON *instead of* the text report, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },

    /// Find a font on this machine, or freeze one into the project (ADR-0057).
    ///
    /// CLI-only (ADR-0011): vendoring is a once-per-project act, not a step in the edit
    /// loop, and a subcommand costs the agent nothing until invoked.
    Fonts {
        #[command(subcommand)]
        command: FontsCommand,
    },

    /// Serve the MCP tools over stdio.
    ///
    /// Not one of ADR-0011's nine verbs: the verbs are what an agent calls, and this is
    /// how the agent's client starts the process that offers them.
    Mcp,
}

#[derive(Subcommand)]
enum FontsCommand {
    /// Every font file on this machine, with its faces and their licence status.
    ///
    /// `blocklisted` will be refused by `vendor` and nothing lifts that; `recognised-open`
    /// vendors and records the licence it found; `unknown` vendors only with a
    /// `--licence` you have verified.
    List {
        /// Walk these directories instead of the platform's font directories.
        #[arg(long = "root", value_name = "DIR")]
        roots: Vec<PathBuf>,
        /// Print the canonical JSON *instead of* the text listing, never alongside it.
        #[arg(long)]
        json: bool,
    },
    /// Copy a local font file into the project behind the licence gate, and record its
    /// licence, source and hash in the `fontVendor` table.
    ///
    /// The checks run before any bytes are copied. A blocklisted font is refused with no
    /// override; a font whose licence text is not recognised is refused until you declare
    /// one with `--licence`. It never edits the `fonts` table — the answer echoes the chain
    /// entry to write.
    Vendor {
        /// The project file.
        project: PathBuf,
        /// The local font file to copy. No URL, no family name: a path.
        font: PathBuf,
        /// The licence identifier a human has verified, e.g. `OFL-1.1`. Required when the
        /// font's own licence text is not recognised; ignored by the blocklist.
        #[arg(long, value_name = "IDENTIFIER")]
        licence: Option<String>,
        /// Where the file came from, recorded in the attestation. Defaults to the absolute
        /// path it was copied from.
        #[arg(long, value_name = "TEXT")]
        source: Option<String>,
        /// The path to vendor under, relative to the project. Defaults to `fonts/<name>`.
        #[arg(long = "as", value_name = "PATH")]
        destination: Option<String>,
        /// Print the canonical JSON *instead of* the text report, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },
}

pub fn run<I, T>(args: I) -> ExitCode
where
    I: IntoIterator<Item = T>,
    T: Into<OsString> + Clone,
{
    let cli = match Cli::try_parse_from(args) {
        Ok(cli) => cli,
        Err(e) if e.use_stderr() => {
            // ADR-0011: an invocation error is a finding, with the same object and the
            // same stable codes as everything else, so there is exactly one thing to
            // parse across the surface.
            let report = Report::bad_invocation(e.to_string().trim_end());
            eprint!("{}", montaget_core::wire::render(&report, PLAIN));
            return exit_code(&report);
        }
        // `--help` and `--version` are not failures; clap has the text, and it goes to
        // stdout with a zero exit.
        Err(e) => {
            print!("{e}");
            return ExitCode::SUCCESS;
        }
    };

    match cli.command {
        Command::Validate {
            project,
            json,
            verbose,
        } => {
            let form = Wire::from_flags(json, verbose);
            match run_verb(|| montaget_core::validate(&project)) {
                Ok(report) => {
                    // `println!`, not `print!`: the JSON form ends without a newline.
                    println!("{}", montaget_core::wire::render(&report, form).trim_end());
                    exit_code(&report)
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::CreateProject {
            project,
            width,
            height,
            fps,
            background,
            duration,
            output,
            json,
            verbose,
        } => {
            let form = Wire::from_flags(json, verbose);
            let scaffold = montaget_core::verbs::create_project::Scaffold {
                width,
                height,
                fps,
                background,
                duration,
                output,
            };
            match run_verb(|| {
                montaget_core::verbs::create_project::create_project(&project, &scaffold)
            }) {
                Ok(report) => {
                    println!("{}", montaget_core::wire::render(&report, form).trim_end());
                    exit_code(&report)
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Fmt {
            project,
            check,
            json,
            verbose,
        } => {
            let form = Wire::from_flags(json, verbose);
            // `LAYOUT` is an informational class, so a `--check` on a pretty-printed file
            // prints one counted line unless the caller asked for more. The findings are
            // in the canonical JSON either way (ADR-0006).
            let mode = if check {
                montaget_core::verbs::fmt::Mode::Check
            } else {
                montaget_core::verbs::fmt::Mode::Write
            };
            match run_verb(|| montaget_core::verbs::fmt::fmt(&project, mode)) {
                Ok(report) => {
                    println!("{}", montaget_core::wire::render(&report, form).trim_end());
                    exit_code(&report)
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Probe {
            sources,
            json,
            verbose,
        } => {
            let form = Wire::from_flags(json, verbose);
            match run_verb(|| montaget_core::verbs::probe::probe(&sources)) {
                Ok(Ok(answer)) => {
                    // The same two lines as `validate`: one core call, one `wire::render`,
                    // one exit code. The adapter decides nothing about the wire format.
                    println!(
                        "{}",
                        montaget_core::wire::render_answer(&answer, form).trim_end()
                    );
                    exit_code(answer.report())
                }
                // No `ffprobe`, so there are no media numbers. ADR-0011's exit 70.
                Ok(Err(report)) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Timeline { project, json } => {
            // `--verbose` is deliberately absent, so `false` here is the only form there is
            // rather than a flag the adapter decided for the caller.
            let form = Wire::from_flags(json, false);
            match run_verb(|| montaget_core::verbs::timeline::timeline(&project)) {
                Ok(answer) => {
                    println!(
                        "{}",
                        montaget_core::wire::render_timeline(&answer, form).trim_end()
                    );
                    exit_code(answer.report())
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Query {
            project,
            at,
            from,
            to,
            predicate,
            census,
            json,
        } => {
            // `--verbose` is deliberately absent, so `false` here is the only form there is
            // rather than a flag the adapter decided for the caller.
            let form = Wire::from_flags(json, false);
            // Which combinations of these flags are legal is the verb's rule, not argv's:
            // the MCP surface takes the same four arguments with no `clap` to arrange them,
            // and a `clap` argument group would leave that surface uncovered (ADR-0011).
            let ask = montaget_core::verbs::query::Ask {
                at,
                from,
                to,
                predicate,
                census,
            };
            match run_verb(|| montaget_core::verbs::query::query(&project, &ask)) {
                Ok(answer) => {
                    println!(
                        "{}",
                        montaget_core::wire::render_query(&answer, form).trim_end()
                    );
                    exit_code(answer.report())
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Frame {
            project,
            at,
            out,
            crop,
            full,
            png,
            json,
        } => {
            // `--verbose` is deliberately absent, so `false` here is the only form there is
            // rather than a flag the adapter decided for the caller.
            let form = Wire::from_flags(json, false);
            // Whether the flags ask for a frame at all — a missing `--at`, an unparseable
            // `--crop` — is the verb's rule and not argv's: the MCP surface takes the same
            // arguments with no `clap` to arrange them, and a `clap` requirement here would
            // leave that surface uncovered (ADR-0011).
            let ask = montaget_core::verbs::frame::Ask {
                at,
                crop,
                full,
                png,
                out: Some(out),
            };
            match run_verb(|| montaget_core::verbs::frame::frame(&project, &ask)) {
                Ok(answer) => {
                    println!(
                        "{}",
                        montaget_core::wire::render_frame(&answer, form).trim_end()
                    );
                    exit_code(answer.report())
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Measure {
            project,
            element,
            at,
            elements,
            all,
            json,
        } => {
            // `--verbose` is deliberately absent, so `false` here is the only form there is
            // rather than a flag the adapter decided for the caller.
            let form = Wire::from_flags(json, false);
            // The one thing argv must do that the MCP surface does not: an element arrives
            // there as an object and here as a string. Parsing it is transport, not a rule
            // — and a string that is not JSON is an invocation error, which is the same
            // finding with the same code either way (ADR-0011). `--at` needs no such step.
            let element = match element {
                Some(element) => match serde_json::from_str(&element) {
                    Ok(element) => Some(element),
                    Err(e) => {
                        let report =
                            Report::bad_invocation(format!("`--element` is not valid JSON: {e}"));
                        eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                        return exit_code(&report);
                    }
                },
                None => None,
            };
            // `--elements` is transport the same way: a JSON *array* of specs, and a string
            // that does not parse as one is a whole-call refusal (ADR-0011's exit 3), not a
            // per-slot error — #317 draws that line at the request, not at one element in it.
            let elements = match elements {
                Some(elements) => match serde_json::from_str::<Vec<serde_json::Value>>(&elements) {
                    Ok(elements) => Some(elements),
                    Err(e) => {
                        let report = Report::bad_invocation(format!(
                            "`--elements` is not a valid JSON array: {e}"
                        ));
                        eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                        return exit_code(&report);
                    }
                },
                None => None,
            };
            let ask = montaget_core::verbs::measure::Ask {
                element,
                at,
                elements,
                all,
            };
            match run_verb(|| montaget_core::verbs::measure::measure(&project, &ask)) {
                Ok(answer) => {
                    println!(
                        "{}",
                        montaget_core::wire::render_measure(&answer, form).trim_end()
                    );
                    exit_code(answer.report())
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Render {
            project,
            from,
            to,
            output,
            json,
            verbose,
        } => {
            let form = Wire::from_flags(json, verbose);
            // Which combinations of `--from`/`--to`/`--output` are legal is the verb's rule
            // and not argv's: the MCP surface takes the same arguments with no `clap` to
            // arrange them (ADR-0011).
            let ask = montaget_core::verbs::render::Ask { from, to, output };
            // ADR-0011's split, made here: the result is stdout's and progress is
            // stderr's, coarse — a tenth at a time, with the wall clock beside it so the
            // caller can budget the next call.
            let mut progress = |p: montaget_core::verbs::render::Progress| {
                eprintln!(
                    "render  {}/{} frames  {:.1} s",
                    p.done,
                    p.of,
                    p.elapsed.as_secs_f64()
                );
            };
            match run_verb(std::panic::AssertUnwindSafe(|| {
                montaget_core::verbs::render::render(&project, &ask, &mut progress)
            })) {
                Ok(answer) => {
                    println!(
                        "{}",
                        montaget_core::wire::render_video(&answer, form).trim_end()
                    );
                    exit_code(answer.report())
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Preview {
            project,
            from,
            to,
            output,
            full,
            json,
            verbose,
        } => {
            let form = Wire::from_flags(json, verbose);
            // `clock` is deliberately absent: ADR-0021's `<5 s` is the budget, and an
            // adapter that let argv restate it would be argv holding a number the ADR
            // holds.
            let ask = montaget_core::verbs::preview::Ask {
                from,
                to,
                output,
                full,
                clock: montaget_core::verbs::preview::Clock::Scrub,
            };
            // ADR-0011's split again, and the tier named on every line: a rung that is
            // abandoned on the budget has already printed progress, and a reader who saw
            // "preview 3/5" twice needs to know the second pass is a smaller frame.
            let mut progress = |p: montaget_core::verbs::render::Progress| {
                eprintln!(
                    "preview  {}/{} frames  {:.1} s",
                    p.done,
                    p.of,
                    p.elapsed.as_secs_f64()
                );
            };
            match run_verb(std::panic::AssertUnwindSafe(|| {
                montaget_core::verbs::preview::preview(&project, &ask, &mut progress)
            })) {
                Ok(answer) => {
                    println!(
                        "{}",
                        montaget_core::wire::render_preview(&answer, form).trim_end()
                    );
                    exit_code(answer.report())
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Shift {
            project,
            at,
            delta,
            scope,
            release,
            json,
            verbose,
        } => {
            let form = Wire::from_flags(json, verbose);
            let release = match parse_release(&release) {
                Ok(release) => release,
                Err(reason) => {
                    let report = Report::bad_invocation(reason);
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    return exit_code(&report);
                }
            };
            let ask = montaget_core::verbs::shift::Ask {
                at,
                delta,
                scope,
                release,
            };
            match run_verb(|| montaget_core::verbs::shift::shift(&project, &ask)) {
                Ok(answer) => {
                    println!(
                        "{}",
                        montaget_core::wire::render_shift(&answer, form).trim_end()
                    );
                    exit_code(answer.report())
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Compare {
            reference,
            current,
            json,
            verbose,
        } => {
            let form = Wire::from_flags(json, verbose);
            match run_verb(|| montaget_core::verbs::compare::compare(&reference, &current)) {
                Ok(report) => {
                    println!("{}", montaget_core::wire::render(&report, form).trim_end());
                    exit_code(&report)
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Fonts {
            command: FontsCommand::List { roots, json },
        } => {
            // `--verbose` is deliberately absent: the listing is the answer and is never
            // collapsed. No `--root` is passed through as no roots; which directories are
            // the platform's is the core's to say.
            let form = Wire::from_flags(json, false);
            match run_verb(|| montaget_core::verbs::fonts::list(&roots)) {
                Ok(answer) => {
                    println!(
                        "{}",
                        montaget_core::wire::render_fonts_list(&answer, form).trim_end()
                    );
                    exit_code(answer.report())
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Fonts {
            command:
                FontsCommand::Vendor {
                    project,
                    font,
                    licence,
                    source,
                    destination,
                    json,
                    verbose,
                },
        } => {
            let form = Wire::from_flags(json, verbose);
            let ask = montaget_core::verbs::fonts::Vendor {
                font,
                licence,
                source,
                destination,
            };
            match run_verb(|| montaget_core::verbs::fonts::vendor(&project, &ask)) {
                Ok(answer) => {
                    println!(
                        "{}",
                        montaget_core::wire::render_fonts_vendor(&answer, form).trim_end()
                    );
                    exit_code(answer.report())
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Mcp => match crate::mcp::serve() {
            Ok(()) => ExitCode::SUCCESS,
            Err(e) => {
                let report = Report::internal_failure(e);
                eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                exit_code(&report)
            }
        },
    }
}

/// `--release FROM,TO` repeated, parsed into `shift`'s own argument shape.
fn parse_release(raw: &[String]) -> Result<Vec<(i64, i64)>, String> {
    raw.iter()
        .map(|pair| {
            let (from, to) = pair.split_once(',').ok_or_else(|| {
                format!("`--release {pair}` is not `FROM,TO`: two milliseconds joined by a comma")
            })?;
            let from: i64 = from
                .trim()
                .parse()
                .map_err(|_| format!("`--release {pair}`: `{from}` is not an integer"))?;
            let to: i64 = to
                .trim()
                .parse()
                .map_err(|_| format!("`--release {pair}`: `{to}` is not an integer"))?;
            Ok((from, to))
        })
        .collect()
}

/// Run one verb, turning a panic into ADR-0011's exit 70 rather than an abort.
///
/// Exit 70's stated next move is *"retry or report"*, which needs the process to have
/// exited with 70 and said something. Without this, the failures the code treats as
/// programmer errors — a check emitting an unregistered code, an arithmetic overflow —
/// abort with a Rust backtrace and no finding, and the one exit code reserved for
/// "Montaget broke" would never be produced by Montaget breaking.
/// Generic in what the verb answers with, because the guarantee is about the *panic* and
/// not about the answer: `validate` hands back a `Report`, `probe` and `timeline` hand back
/// their own answer carrying one, and all three need the same exit code when the verb dies
/// mid-run.
fn run_verb<T>(verb: impl FnOnce() -> T + std::panic::UnwindSafe) -> Result<T, Box<Report>> {
    // Boxed on the error side alone: every caller prints a report either way and only the
    // stream differs, and a `Report` is wide enough that carrying one inline widens every
    // call on the happy path.
    std::panic::catch_unwind(verb).map_err(|payload| Box::new(panic_report(payload)))
}

/// The panic's own message, which is what makes exit 70 actionable.
fn panic_report(payload: Box<dyn std::any::Any + Send>) -> Report {
    let what = payload
        .downcast_ref::<&str>()
        .map(|s| s.to_string())
        .or_else(|| payload.downcast_ref::<String>().cloned())
        .unwrap_or_else(|| "a panic carrying no message".to_string());
    Report::internal_failure(what)
}

/// The form a report reaches stderr in: prose, unexpanded. Neither a bad invocation nor
/// an internal failure has informational findings for `--verbose` to expand, and neither
/// has read a `--json` flag that could have asked for the other form.
const PLAIN: Wire = Wire::Text { verbose: false };

fn exit_code(report: &Report) -> ExitCode {
    ExitCode::from(report.exit_code().as_u8())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_panicking_verb_becomes_exit_70_rather_than_an_abort() {
        let report = run_verb(|| panic!("the font stack failed")).expect_err("a panic");

        assert_eq!(
            report.exit_code(),
            montaget_core::report::ExitCode::Internal
        );
        assert_eq!(report.findings[0].code, "E-INTERNAL");
        assert!(
            montaget_core::wire::render(&report, PLAIN).contains("the font stack failed"),
            "the panic's own message is what makes exit 70 actionable"
        );
    }

    #[test]
    fn a_verb_that_returns_normally_is_handed_back_untouched() {
        let report = run_verb(|| Report::new("validate", Some("p.json".into()))).expect("no panic");
        assert_eq!(report.exit_code(), montaget_core::report::ExitCode::Ok);
    }
}
