//! The CLI adapter.
//!
//! It owns argv, the two output forms, and the process exit code — nothing else. Every
//! sentence it prints was generated by `montaget_core::text` from the canonical JSON.

use std::ffi::OsString;
use std::path::PathBuf;
use std::process::ExitCode;

use clap::{Parser, Subcommand};
use montaget_core::Wire;
use montaget_core::report::Report;

#[derive(Parser)]
#[command(
    name = "montaget",
    version,
    about = "A video editor whose project format is authored by an agent.",
    disable_help_subcommand = true
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Does the document agree with itself and with the disk?
    Validate {
        /// The project file.
        project: PathBuf,
        /// Print the canonical JSON *instead of* the text report, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },
    /// Rewrite the file in the canonical convention.
    ///
    /// CLI-only (ADR-0011), and split in two (ADR-0041): `--check` reports what a
    /// rewrite would change and writes nothing; bare `fmt` writes.
    Fmt {
        /// The project file.
        project: PathBuf,
        /// Report what a rewrite would change, without touching the file.
        #[arg(long)]
        check: bool,
        /// Print the canonical JSON *instead of* the text report, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },
    /// What are this media file's numbers?
    ///
    /// CLI-only (ADR-0011): an MCP tool schema costs the agent context on every turn,
    /// and a subcommand costs nothing until invoked.
    Probe {
        /// The media files or URLs to probe. A relative path resolves against the working
        /// directory (ADR-0053).
        #[arg(required = true)]
        sources: Vec<String>,
        /// Print the canonical JSON *instead of* the text report, never alongside it.
        #[arg(long)]
        json: bool,
        /// Expand the informational classes that collapse to one counted line.
        #[arg(long)]
        verbose: bool,
    },
    /// Serve the MCP tools over stdio.
    ///
    /// Not one of ADR-0011's nine verbs: the verbs are what an agent calls, and this is
    /// how the agent's client starts the process that offers them.
    Mcp,
}

pub fn run<I, T>(args: I) -> ExitCode
where
    I: IntoIterator<Item = T>,
    T: Into<OsString> + Clone,
{
    let cli = match Cli::try_parse_from(args) {
        Ok(cli) => cli,
        Err(e) if e.use_stderr() => {
            // ADR-0011: an invocation error is a finding, with the same object and the
            // same stable codes as everything else, so there is exactly one thing to
            // parse across the surface.
            let report = Report::bad_invocation(e.to_string().trim_end());
            eprint!("{}", montaget_core::wire::render(&report, PLAIN));
            return exit_code(&report);
        }
        // `--help` and `--version` are not failures; clap has the text, and it goes to
        // stdout with a zero exit.
        Err(e) => {
            print!("{e}");
            return ExitCode::SUCCESS;
        }
    };

    match cli.command {
        Command::Validate {
            project,
            json,
            verbose,
        } => {
            let form = Wire::from_flags(json, verbose);
            match run_verb(|| montaget_core::validate(&project)) {
                Ok(report) => {
                    // `println!`, not `print!`: the JSON form ends without a newline.
                    println!("{}", montaget_core::wire::render(&report, form).trim_end());
                    exit_code(&report)
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Fmt {
            project,
            check,
            json,
            verbose,
        } => {
            let form = Wire::from_flags(json, verbose);
            // `LAYOUT` is an informational class, so a `--check` on a pretty-printed file
            // prints one counted line unless the caller asked for more. The findings are
            // in the canonical JSON either way (ADR-0006).
            let mode = if check {
                montaget_core::verbs::fmt::Mode::Check
            } else {
                montaget_core::verbs::fmt::Mode::Write
            };
            match run_verb(|| montaget_core::verbs::fmt::fmt(&project, mode)) {
                Ok(report) => {
                    println!("{}", montaget_core::wire::render(&report, form).trim_end());
                    exit_code(&report)
                }
                Err(report) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Probe {
            sources,
            json,
            verbose,
        } => {
            let form = Wire::from_flags(json, verbose);
            let probed = std::panic::catch_unwind(|| montaget_core::verbs::probe::probe(&sources));

            match probed {
                Ok(Ok(answer)) => {
                    // The same two lines as `validate`: one core call, one `wire::render`,
                    // one exit code. The adapter decides nothing about the wire format.
                    println!(
                        "{}",
                        montaget_core::wire::render_answer(&answer, form).trim_end()
                    );
                    exit_code(answer.report())
                }
                // No `ffprobe`, so there are no media numbers. ADR-0011's exit 70.
                Ok(Err(report)) => {
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
                Err(payload) => {
                    let report = panic_report(payload);
                    eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                    exit_code(&report)
                }
            }
        }
        Command::Mcp => match crate::mcp::serve() {
            Ok(()) => ExitCode::SUCCESS,
            Err(e) => {
                let report = Report::internal_failure(e);
                eprint!("{}", montaget_core::wire::render(&report, PLAIN));
                exit_code(&report)
            }
        },
    }
}

/// Run one verb, turning a panic into ADR-0011's exit 70 rather than an abort.
///
/// Exit 70's stated next move is *"retry or report"*, which needs the process to have
/// exited with 70 and said something. Without this, the failures the code treats as
/// programmer errors — a check emitting an unregistered code, an arithmetic overflow —
/// abort with a Rust backtrace and no finding, and the one exit code reserved for
/// "Montaget broke" would never be produced by Montaget breaking.
fn run_verb(verb: impl FnOnce() -> Report + std::panic::UnwindSafe) -> Result<Report, Box<Report>> {
    // Boxed on the error side alone: both arms carry a report and only the stream they
    // print to differs, and a `Report` is wide enough that carrying two inline widens every
    // call on the happy path.
    std::panic::catch_unwind(verb).map_err(|payload| Box::new(panic_report(payload)))
}

/// The panic's own message, which is what makes exit 70 actionable.
fn panic_report(payload: Box<dyn std::any::Any + Send>) -> Report {
    let what = payload
        .downcast_ref::<&str>()
        .map(|s| s.to_string())
        .or_else(|| payload.downcast_ref::<String>().cloned())
        .unwrap_or_else(|| "a panic carrying no message".to_string());
    Report::internal_failure(what)
}

/// The form a report reaches stderr in: prose, unexpanded. Neither a bad invocation nor
/// an internal failure has informational findings for `--verbose` to expand, and neither
/// has read a `--json` flag that could have asked for the other form.
const PLAIN: Wire = Wire::Text { verbose: false };

fn exit_code(report: &Report) -> ExitCode {
    ExitCode::from(report.exit_code().as_u8())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_panicking_verb_becomes_exit_70_rather_than_an_abort() {
        let report = run_verb(|| panic!("the font stack failed")).expect_err("a panic");

        assert_eq!(
            report.exit_code(),
            montaget_core::report::ExitCode::Internal
        );
        assert_eq!(report.findings[0].code, "E-INTERNAL");
        assert!(
            montaget_core::wire::render(&report, PLAIN).contains("the font stack failed"),
            "the panic's own message is what makes exit 70 actionable"
        );
    }

    #[test]
    fn a_verb_that_returns_normally_is_handed_back_untouched() {
        let report = run_verb(|| Report::new("validate", Some("p.json".into()))).expect("no panic");
        assert_eq!(report.exit_code(), montaget_core::report::ExitCode::Ok);
    }
}
